/**
 * This file is used to contain all the constants within the application.
 */
/* Creating INIT_APP API error code constants */
var init_app_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	UPDATE_REQUIRED : "INIT_APP_UPDATE_REQUIRED"
};

/* Creating USER_AUTH API error code constants */
var user_auth_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	EXPIRED_PASSWORD : "USER_AUTH_EXPIRED_PWD",
	BAD_CREDENTIALS : "USER_AUTH_BAD_CREDENTIALS",
	ACCOUNT_LOCKED : "USER_AUTH_ACCOUNT_LOCKED",
	NEED_ACCEPTANCE : "USER_AUTH_TERMS_NEED_ACCEPTANCE",
	USER_MISMATCH : "USER_TERMS_USER_MISMATCH",
	TERMS_NOT_FOUND : "USER_TERMS_TERMS_NOT_FOUND",
	TYPE_MISMATCH : "USER_TERMS_TYPE_MISMATCH"
};

/* Creating USER_TERMS API error code constants */
var user_terms_constant = {
// TO-DO
};

/* Creating USER_SEC_QUES API error code constants */
var user_sec_ques_constant = {
// TO-DO
};

/* Creating USER_SEND_TEMP_PWD API error code constants */
var user_send_temp_pwd_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	USER_SEND_TEMP_PWD_USER_NOT_FOUND : "USER_SEND_TEMP_PWD_USER_NOT_FOUND",
	USER_SEND_TEMP_PWD_WRONG_SEC_ANSWER : "USER_SEND_TEMP_PWD_WRONG_SEC_ANSWER",
	USER_SEND_TEMP_PWD_INVALID_PHONE : "USER_SEND_TEMP_PWD_INVALID_PHONE",
	USER_SEND_TEMP_PWD_USER_LOCKED : "USER_SEND_TEMP_PWD_USER_LOCKED"
};

/* Creating USER_RESET_PWD API error code constants */
var user_reset_pwd_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	USER_RESET_PWD_USER_MISMATCH : "USER_RESET_PWD_USER_MISMATCH",
	USER_RESET_PWD_INVALID_PWD : "USER_RESET_PWD_INVALID_PWD",
	USER_RESET_PWD_NOT_TEMP : "USER_RESET_PWD_NOT_TEMP"
};

/* Creating USER_GET_PROFILE API error code constants */
var user_get_profile_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	USER_GET_PROFILE : "USER_GET_PROFILE_USERID"
};

/* Creating USER_UPD_PROFILE API error code constants */
var user_upd_profile_constant = {
		USER_UPD_PROFILE_PHONE : "USER_UPD_PROFILE_PHONE",
		USER_UPD_PROFILE_FIRST_NAME : "USER_UPD_PROFILE_FIRST_NAME",
		USER_UPD_PROFILE_LAST_NAME : "USER_UPD_PROFILE_LAST_NAME",
		USER_UPD_PROFILE_EMAIL : "USER_UPD_PROFILE_EMAIL",
		USER_UPD_PROFILE_CONTACT : "USER_UPD_PROFILE_CONTACT",
		USER_UPD_PROFILE_STATE : "USER_UPD_PROFILE_STATE",
		USER_UPD_PROFILE_ZIP : "USER_UPD_PROFILE_ZIP",
		USER_UPD_PROFILE_CURR_PWD : "USER_UPD_PROFILE_CURR_PWD",
		USER_UPD_PROFILE_NEW_PWD : "USER_UPD_PROFILE_NEW_PWD",
		USER_UPD_PROFILE_SEC_ANSWER : "USER_UPD_PROFILE_SEC_ANSWER",
		USER_UPD_PROFILE_ADDRESS : "USER_UPD_PROFILE_ADDRESS",
		USER_UPD_PROFILE_USERID : "USER_UPD_PROFILE _USERID",
		USER_UPD_PROFILE_INVALID_APPLICATION_ID : "INVALID_APPLICATION_ID",
		USER_UPD_PROFILE_PWD_USERNAME_MATCH : "USER_UPD_PROFILE_PWD_USERNAME_MATCH",
		USER_UPD_PROFILE_DUPLICATE_USERNAME : "USER_UPD_PROFILE_DUPLICATE_USERNAME"
};

/* Creating USER_INIT_REG API error code constants */
var user_init_reg_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	USER_INT_REG_DUPLICATE_USERNAME : "USER_INT_REG_DUPLICATE_USERNAME",
	USER_INT_REG_BAD_USERNAME : "USER_INT_REG_BAD_USERNAME",
	USER_INT_REG_BAD_PASSWORD : "USER_INT_REG_BAD_PASSWORD",
	USER_INT_REG_BAD_TERMS_ID : "USER_INT_REG_BAD_TERMS_ID",
	USER_INT_REG_INVALID_PHONE : "USER_INT_REG_INVALID_PHONE",
	USER_INT_REG_INVALID_QUESTION : "USER_INT_REG_INVALID_QUESTION",
	USER_INT_REG_INVALID_ANSWER : "USER_INT_REG_INVALID_ANSWER",
	USER_INT_REG_INVALID_PIN : "USER_INT_REG_INVALID_PIN",
	USER_INT_REG_FAILURE : "USER_INT_REG_FAILURE",
	USER_INT_REG_BAD_EMAIL : "USER_INT_REG_BAD_EMAIL",
	USER_INT_REG_INVALID_PARAM : "USER_INT_REG_INVALID_PARAM",
	USER_INT_REG_EMAIL_USERNAME_MISMATCH : "USER_INT_REG_EMAIL_USERNAME_MISMATCH"
};

/* Creating USER_GUEST API error code constants */
var user_guest_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	USER_GUEST_BAD_TERMS_ID : "USER_GUEST_BAD_TERMS_ID",
	USER_GUEST_FAILURE : "USER_GUEST_FAILURE"
};

/* Creating UPGRADE_GUEST_USER API error code constants */
var upgrade_guest_user_constant = {
	NVALID_APP_ID : "INVALID_APPLICATION_ID",
	USER_GUEST_BAD_TERMS_ID : "USER_GUEST_BAD_TERMS_ID",
	USER_GUEST_INVALID_PHONE : "USER_GUEST_INVALID_PHONE",
	USER_GUEST_BAD_EMAIL : "USER_GUEST_BAD_EMAIL",
	USER_GUEST_FEATURE_DISABLED : "USER_GUEST_FEATURE_DISABLED",
	USER_GUEST_PHONE_EXIST : "USER_GUEST_PHONE_EXIST",
	USER_GUEST_FAILURE : "USER_GUEST_FAILURE",
	USER_UPD_PROFILE_DUPLICATE_USERNAME : "USER_UPD_PROFILE_DUPLICATE_USERNAME",
	USER_UPD_GUEST_USERID : "USER_UPD_GUEST_USERID"
};

/* Creating BP_BILLER_CORP_SEARCH API error code constants */
var bp_biller_corp_search_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	BP_BILLER_SEARCH_CRITERIA : "BP_BILLER_SEARCH_CRITERIA",
	BP_BILLER_SEARCH_MORE_RESULTS : "BP_BILLER_SEARCH_MORE_RESULTS",
	USER_MISMATCH : "USER_TERMS_USER_MISMATCH"
};

/* Creating BP_BILLER_CORD_CREDS API error code constants */
var bp_biller_corp_creds_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	BP_BILLER_CREDS_PROG_ID : "BP_BILLER_CREDS_PROG_ID",
	BP_SAVE_ACCT_CREDS_NICKNAME : "BP_SAVE_ACCT_CREDS_NICKNAME",
	BP_SAVE_ACCT_CREDS_PROG_ID : "BP_SAVE_ACCT_CREDS_PROG_ID",
	BP_SAVE_ACCT_CREDS_CRED_ID : "BP_SAVE_ACCT_CREDS_CRED_ID",
	BP_SAVE_ACCT_CREDS_VALUE : "BP_SAVE_ACCT_CREDS_VALUE",
	BP_SAVE_ACCT_CREDS_BILLER_ACCT : "BP_SAVE_ACCT_CREDS_BILLER_ACCT",
	BP_SAVE_ACCT_CREDS_COUNT : "BP_SAVE_ACCT_CREDS_COUNT",
	BP_SAVE_ACCT_CREDS_REQUIRED : "BP_SAVE_ACCT_CREDS_REQUIRED",
	BP_INVALID_ACCT_NUMBER : "BP_INVALID_ACCT_NUMBER",
	BP_TOO_MANY_BILLERS : "BP_TOO_MANY_BILLERS",
	BP_INVALID_ACCT_ZIP : "BP_INVALID_ACCT_ZIP",
	BP_INVALID_PARAM : "INVALID_PARAM",
	BP_BILLER_CORP_CREDS : "BP_BILLER_CORP_CREDS",
	BP_INACTIVE_EXTERNAL_MERCH_ID : "INACTIVE_EXTERNAL_MERCH_ID",
	BP_INVALID_EXTERNAL_MERCH_ID : "INVALID_EXTERNAL_MERCH_ID",
	BP_SAVE_CREDS : "BP_SAVE_ACCT_CREDS_ACCT_ID",
	USER_MISMATCH : "USER_MISMATCH"
};

/* Creating BP_GET_CORP_ACCOUNT API error code constants */
var bp_get_corp_account_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	BP_SAVE_CREDS : "BP_SAVE_ACCT_CREDS_ACCT_ID",
	USER_MISMATCH : "USER_MISMATCH",
	BP_INVALID_PARAM : "INVALID_PARAM",
	EDIT_BP_GET_ACCOUNT_BILLER_ACCT_CREDS_NOT_FOUND : "BP_GET_ACCOUNT_BILLER_ACCT_CREDS_NOT_FOUND"
};

/* Creating BP_SAVE_BILLER_CORP_ACCT_CREDS API error code constants */
var bp_save_biller_corp_acct_creds_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	BP_BILLER_CREDS_PROG_ID : "BP_BILLER_CREDS_PROG_ID",
	BP_SAVE_ACCT_CREDS_NICKNAME : "BP_SAVE_ACCT_CREDS_NICKNAME",
	BP_SAVE_ACCT_CREDS_PROG_ID : "BP_SAVE_ACCT_CREDS_PROG_ID",
	BP_SAVE_ACCT_CREDS_CRED_ID : "BP_SAVE_ACCT_CREDS_CRED_ID",
	BP_SAVE_ACCT_CREDS_VALUE : "BP_SAVE_ACCT_CREDS_VALUE",
	BP_SAVE_ACCT_CREDS_BILLER_ACCT : "BP_SAVE_ACCT_CREDS_BILLER_ACCT",
	BP_SAVE_ACCT_CREDS_COUNT : "BP_SAVE_ACCT_CREDS_COUNT",
	BP_SAVE_ACCT_CREDS_REQUIRED : "BP_SAVE_ACCT_CREDS_REQUIRED",
	BP_INVALID_ACCT_NUMBER : "BP_INVALID_ACCT_NUMBER",
	BP_TOO_MANY_BILLERS : "BP_TOO_MANY_BILLERS",
	BP_INVALID_ACCT_ZIP : "BP_INVALID_ACCT_ZIP",
	BP_INVALID_PARAM : "INVALID_PARAM",
	BP_BILLER_CORP_CREDS : "BP_BILLER_CORP_CREDS",
	BP_INACTIVE_EXTERNAL_MERCH_ID : "INACTIVE_EXTERNAL_MERCH_ID",
	BP_INVALID_EXTERNAL_MERCH_ID : "INVALID_EXTERNAL_MERCH_ID",
	BP_SAVE_CREDS : "BP_SAVE_ACCT_CREDS_ACCT_ID",
	BP_SAVE_ACCT_CREDS_REGISTRATION_FAILURE : "BP_SAVE_ACCT_CREDS_REGISTRATION_FAILURE",
	USER_MISMATCH : "USER_MISMATCH"
};

/* Creating BP_ACCOUNT_LITE API error code constants */
var bp_account_lite_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	USER_MISMATCH : "USER_MISMATCH",
	BP_CREDS : "BP_CREDS",
	BP_BILLER : "BP_BILLER"
};

/* Creating BP_GET_PENDING_TRANSACTION API error code constants */
var bp_get_pending_transaction_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	USER_MISMATCH : "USER_MISMATCH",
	BP_CART_NOT_FOUND : "BP_CART_NOT_FOUND",
	BP_CART_USER : "BP_CART_USER"
};

/* Creating BP_HIST API error code constants */
var bp_hist_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	USER_MISMATCH : "USER_MISMATCH",
	BP_HIST_DATES : "BP_HIST_DATES",
	BP_HIST_COUNT : "BP_HIST_COUNT"
};

/* Creating BP_SCHEDULE_PAYMENT_HIST API error code constants */
var bp_scheduled_payment_hist_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	USER_MISMATCH : "USER_MISMATCH"
};

/* Creating BP_CANCEL_SCHEDULE_PAYMENT API error code constants */
var bp_cancel_scheduled_payment_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	USER_MISMATCH : "USER_MISMATCH"
};

/* Creating BP_REMOVE_BILLER_CORP_ACCOUNT API error code constants */
var bp_remove_biller_corp_account_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	USER_MISMATCH : "USER_MISMATCH",
	BP_REMOVE_ACCT : "BP_REMOVE_ACCT"
};

/* Creating BP_CALC_SUMBIT_DATE API error code constants */
var bp_calc_submit_date_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID"
};

/* Creating BP_ADD_VERIFY_CART_ITEM API error code constants */
var bp_add_verify_cart_item_constant = {
	INVALID_APPLICATION_ID : "INVALID_APPLICATION_ID",
	USER_MISMATCH : "USER_MISMATCH",
	BP_CART_CHECKOUT_FEATURE_DISABLED : "BP_CART_CHECKOUT_FEATURE_DISABLED",
	BP_CART_NOT_FOUND : "BP_CART_NOT_FOUND",
	BP_CART_FINISHED : "BP_CART_FINISHED",
	BP_CART_PROCESSING : "BP_CART_PROCESSING",
	BP_VELOCITY : "BP_VELOCITY"
};

/* Creating BP_VERIFY_FUNDING_SOURCES_3_2 API error code constants */
var bp_verify_funding_sources_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	BP_FUNDING_SOURCE_OVER : "BP_FUNDING_SOURCE_OVER",
	BP_FUNDING_SOURCE_UNDER : "BP_FUNDING_SOURCE_UNDER",
	BP_PROMO_WILL_EXPIRE_BEFORE_SCHEDULED_PAYMENT_DUE : "BP_PROMO_WILL_EXPIRE_BEFORE_SCHEDULED_PAYMENT_DUE",
	BP_PROMO_WILL_EXPIRE_BEFORE_SCHEDULED_PAYMENT_DUE : "BP_PROMO_WILL_EXPIRE_BEFORE_SCHEDULED_PAYMENT_DUE"
};

/* Creating BP_VALIDATE_PROMO_CODE API error code constants */
var bp_validat_promo_code_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	BP_FUNDING_SOURCE_OVER : "BP_FUNDING_SOURCE_OVER",
	BP_FUNDING_SOURCE_UNDER : "BP_FUNDING_SOURCE_UNDER",
	PROMO_CODE_EXPIRE_MESSAGE : "BP_PROMO_WILL_EXPIRE_BEFORE_SCHEDULED_PAYMENT_DUE",
	BP_PROMO_WILL_EXPIRE_BEFORE_SCHEDULED_PAYMENT_DUE : "BP_PROMO_WILL_EXPIRE_BEFORE_SCHEDULED_PAYMENT_DUE",
	BP_PROMO_CODE_BELOW_MIN_PAYMENT_AMOUNT : "BP_PROMO_CODE_BELOW_MIN_PAYMENT_AMOUNT",
	BP_PROMO_CODE_LIMIT_REACHED : "BP_PROMO_CODE_LIMIT_REACHED",
	BP_PROMO_EXPIRED : "BP_PROMO_EXPIRED"
};

/* Creating BP_SUBMIT_PAYMENT_GROUP API error code constants */
var bp_submit_payment_group_constant = {
	BP_SUBMIT_CART_INVALID_APPLICATION_ID : "INVALID_APPLICATION_ID",
	BP_SUBMIT_CART_USER_MISMATCH : "BP_SUBMIT_CART_USER_MISMATCH",
	BP_SUBMIT_CART_BP_ACCT : "BP_SUBMIT_CART_BP_ACCT",
	BP_SUBMIT_CART_BP_AMOUNT : "BP_SUBMIT_CART_BP_AMOUNT",
	BP_SUBMIT_CART_BP_BILLER : "BP_SUBMIT_CART_BP_BILLER",
	BP_SUBMIT_CART_BP_PAY_BILLS_CREDS : "BP_SUBMIT_CART_BP_PAY_BILLS_CREDS",
	BP_SUBMIT_CART_BP_PROCESS_FAIL : "BP_SUBMIT_CART_BP_PROCESS_FAIL",
	BP_SUBMIT_CART_BP_CART_CHECKOUT_FEATURE_DISABLED : "BP_SUBMIT_CART_BP_CART_CHECKOUT_FEATURE_DISABLED",
	BP_SUBMIT_CART_BP_NO_CART_ITEMS : "BP_SUBMIT_CART_BP_NO_CART_ITEMS",
	BP_SUBMIT_CART_BP_VELOCITY : "BP_SUBMIT_CART_BP_VELOCITY",
	BP_SUBMIT_CART_BP_FUNDING_SOURCE_FAILED : "BP_SUBMIT_CART_BP_FUNDING_SOURCE_FAILED",
	BP_SUBMIT_CART_BP_FUNDING_SOURCE_OVER : "BP_SUBMIT_CART_BP_FUNDING_SOURCE_OVER",
	BP_SUBMIT_CART_BP_FUNDING_SOURCE_UNDER : "BP_SUBMIT_CART_BP_FUNDING_SOURCE_UNDER",
	BP_SUBMIT_CARRT_BP_CARD_NOT_ALLOWED_SCHEDULED : "BP_SUBMIT_CARRT_BP_CARD_NOT_ALLOWED_SCHEDULED",
	BP_CARD_NOT_ALLOWED_FOR_SCHEDULED_PAYMENTS : "BP_CARD_NOT_ALLOWED_FOR_SCHEDULED_PAYMENTS"
};

/* Creating BP_CHECK_PAYMENT_GROUP_STATUS API error code constants */
var bp_check_payment_group_status_constant = {
	CHECK_CART_STATUS_INVALID_APPLICATION_ID : "INVALID_APPLICATION_ID",
	CHECK_CART_STATUS_USER_MISMATCH : "USER_MISMATCH",
	CHECK_CART_STATUS_BP_CART_NOT_FOUND : "BP_CART_NOT_FOUND",
	INCOMPLETE_FAILED : "INCOMPLETE_FAILED"
};

/* Creating BP_CART_HIST API error code constants */
var bp_cart_hist_constant = {
		INVALID_APPLICATION_ID_SUMMARY : "INVALID_APPLICATION_ID",
		USER_MISMATCH_SUMMARY : "USER_MISMATCH"
};

/* Creating BP_CART_RECEIPT API error code constants */
var bp_cart_receipt_constant = {

};

/* Creating BP_CART_RECEIPT_REPRINT API error code constants */
var bp_cart_receipt_reprint_constant = {

};

/* Creating CM_GET_PAYMENT_CARD API error code constants */
var cm_get_payment_card_constant = {
	INVALID_APP_ID : "INVALID_APPLICATION_ID",
	USER_MISMATCH : "USER_MISMATCH",
	CM_CHECKOUT_FEATURE_DISABLED : "CM_CHECKOUT_FEATURE_DISABLED",
	CM_INVALID_FUNDING_PARTNER : "CM_INVALID_FUNDING_PARTNER"
};

/* Creating CM_ADD_PAYMENT_CARD API error code constants */
var cm_add_payment_card_constant = {
	INVALID_APPLICATION_ID_CARD : "INVALID_APPLICATION_ID",
	USER_MISMATCH_CARD : "USER_MISMATCH_CARD",
	INVALID_PARAM_CARD : "INVALID_PARAM_CARD",
	CM_CARD_LIMIT_REACHED_CARD : "CM_CARD_LIMIT_REACHED_CARD",
	CM_VESTA_SYSTEM_ERROR : "CM_VESTA_SYSTEM_ERROR",
	CM_VESTA_MISSING_CARD_INFO : "CM_VESTA_MISSING_CARD_INFO",
	CM_VESTA_INVALID_CARD_LENGTH : "CM_VESTA_INVALID_CARD_LENGTH",
	CM_VESTA_ACCOUNT_NOT_ACTIVE : "CM_VESTA_ACCOUNT_NOT_ACTIVE",
	CM_TENDER_TYPE_MISMATCH : "CM_TENDER_TYPE_MISMATCH"	
};

/* Creating CM_EDIT_PAYMENT_CARD API error code constants */
var cm_edit_payment_card_constant = {
	INVALID_APPLICATION_ID : "INVALID_APPLICATION_ID",
	USER_MISMATCH : "USER_MISMATCH",
	INVALID_PARAM : "INVALID_PARAM",
	BP_CHECKOUT_FEATURE_DISABLED : "BP_CHECKOUT_FEATURE_DISABLED",
	BP_INVALID_FUNDING_PARTNER : "BP_INVALID_FUNDING_PARTNER",
	CM_CARD_NOT_FOUND : "CM_CARD_NOT_FOUND",
	CM_VESTA_MISSING_OR_INVALID_CARD_INFO : "CM_VESTA_MISSING_OR_INVALID_CARD_INFO",
	BP_EDIT_CARD_CANCELED_SCHEDULED_PAYMENTS: "BP_EDIT_CARD_CANCELED_SCHEDULED_PAYMENTS"	
};

/* Creating CM_DELETE_PAYMENT_CARD API error code constants */
var cm_delete_payment_card_constant = {
	INVALID_APPLICATION_ID : "INVALID_APPLICATION_ID",
	BP_CHECKOUT_FEATURE_DISABLED : "BP_CHECKOUT_FEATURE_DISABLED",
	CM_CARD_NOT_FOUND : "CM_CARD_NOT_FOUND",
	CM_DELETE_CARD_SCHEDULED_PAYMENTS : "CM_DELETE_CARD_SCHEDULED_PAYMENTS"
};

/* Creating LOCATION_LOAD API error code constants */
var location_load_constant = {
	INVALID_APPLICATION_ID : "INVALID_APPLICATION_ID",
	LOCATIONS_LOAD_COUNT : "LOCATIONS_LOAD_COUNT",
	LOCATIONS_LOAD_POSTAL_CODE : "LOCATIONS_LOAD_POSTAL_CODE",
	SYS_ERROR : "SYS_ERROR"
};

/* Creating Common constants for payment status */
var payment_status_constant = {
	PAID : "PAID",
	PENDING : "PENDING",
	IN_PROCESS : "IN_PROCESS",
	SCHEDULED : "SCHEDULED",
	SCHEDULED_PENDING : "SCHEDULED_PENDING",
	SCHEDULED_PROCESSING : "SCHEDULED_PROCESSING",
	SCHEDULED_PAID : "SCHEDULED_PAID",
	FAILED : "FAILED",
	REJECTED : "REJECTED",
	RETURNED : "RETURNED",
	RETURN_PENDING : "RETURN_PENDING",
	VOID : "VOID",
	REVERSED : "REVERSED",
	SCHEDULED_CANCELLED : "SCHEDULED_CANCELLED",
	SCHEDULED_POSTING_CATEGORY_CHANGED : "SCHEDULED_POSTING_CATEGORY_CHANGED",
    SCHEDULED_INVALID_PAYMENT_AMOUNT: "SCHEDULED_INVALID_PAYMENT_AMOUNT",
    SCHEDULED_VELOCITY_LIMIT_EXCEEDED: "SCHEDULED_VELOCITY_LIMIT_EXCEEDED",
	SCHEDULED_PROGRAM_ENDED : "SCHEDULED_PROGRAM_ENDED",
	SCHEDULED_NOT_AUTHED : "SCHEDULED_NOT_AUTHED",
	SCHEDULED_CANCELLED_CARD_NO_LONGER_ELIGIBLE : "SCHEDULED_CANCELLED_CARD_NO_LONGER_ELIGIBLE",
	SCHEDULED_PAYMENT_CARD_FAILED : "SCHEDULED_PAYMENT_CARD_FAILED",
    SCHEDULED_POSTING_WINDOW_EXPIRED: "SCHEDULED_POSTING_WINDOW_EXPIRED",
    SCHEDULED_BAN_VELOCITY_LIMIT_EXCEEDED: "SCHEDULED_BAN_VELOCITY_LIMIT_EXCEEDED",
    SCHEDULED_CANCELLED_CARD_NO_LONGER_AVAILABLE: "SCHEDULED_CANCELLED_CARD_NO_LONGER_AVAILABLE"
};

/* Common constants*/
var constant = {
	THIRTY_DAYS_IN_MILIS : 2592000000,
	DEFAULT : "Default",
	FOURTY_FIVE_DAYS_IN_MILIS : 3888000000,
	ONE_DAY_IN_MILIS : 86400000,
	FIRST_DATEINDEX : 0
};

/* CallFrom constants to identify from where the call has been made*/
var callFrom_constant = {
	SIDE_BAR_CALL : "sideBarCall",
	BILL_STATUS_CALL : "billStatusCall",
	SIDE_BAR_CANCEL_CALL : "sideBarCancelButton",
	BILL_STATUS_MOB_CANCEL_CALL : "billStatusMobCancelButton",
	BILL_STATUS_CANCEL_CALL : "billStatusStandardCall",
	MANAGE_CARD_DELTE_CALL : "manageCardsCallForDelete",
	MANAGE_DELTE_CARD_SCHEDULE_CALL : "manageCallForDeleteCardAndPayments",
	MANAGE_ADD_CARD_CALL : "manageCardCallForAddingCard",
	SECURITY_SAVE_BTN_CALL : "callFromSecuritySaveBtn",
	EDIT_PROFILE_SAVE_BTN_CALL : "callFromEditProfileSaveBtn",
	GUEST_USER_ON_CHECKOUT_CALL : "guestUserOnCheckout",
	MANAGE_CARD_CHECKOUT_CALL : "manageCardsCallForCheckOut",
	MANAGE_CARD_FROM_MAINPAGE	: "callFromMainPage",
	MANAGE_CARD_DELETE	: "deleteCard",
	MANAGE_CARD_ADD_CARD	: "addCard",
	CALL_EDIT_PROFILE_REFRESH : "callFromEditProfile",
	CALL_SECURITY_PROFILE_REFRESH : "callFromEditProfileSecurity",
	FROM_GO_BACK : "FromGoBack"
};

/* All the tender type constants*/
var tenderTypeConstant = {
	DEBIT : "DEBIT", 
	CREDIT : "CREDIT",
	CASH : "CASH",
	PROMO : "PROMO",
	UNKNOWN : "UNKNOWN"
};

/* Cvv required constants*/
var cvvRequiredStatusConstant = {
	REQUIRED : "REQUIRED",
	UNKNOWN : "UNKNOWN"
};

/* Card brand constants */
var cardBrandConstant = {
	MASTERCARD : "MC",
	VISA : "VS",
	DISCOVER : "DC",
	DISCOVER_NEW :"DS"	
};

/* Json type constants for opp */
var jsonTypeConstant = {
		BLACKHAWK : "Blackhawk",
		PRECASH : "PreCash",
		INCOMM : "InComm",
		VESTADEBIT : "DEBIT",
		VESTACREDIT : "CREDIT",
		VESTADEBITVISA : "VestaDebitVisa",
		VESTACREDITVISA : "VestaCreditVisa",
		VESTADEBITMASTER : "VestaDebitMasterCard",
		VESTACREDITMASTER : "VestaCreditMasterCard",
		VESTADEBITDISCOVER : "VestaDebitDiscover",
		VESTACREDITDISCOVER : "VestaCreditDiscover",
		VESTADEBITVISAOTHER : "VestaDebitVisaOther",
		VESTACREDITVISAOTHER : "VestaCreditVisaOther",
		VESTADEBITMASTERCARDOTHER : "VestaDebitMasterCardOther",
		VESTACREDITMASTERCARDOTHER : "VestaCreditMasterCardOther",
		VESTADEBITDISCOVERCARDOTHER : "VestaDebitDiscoverOther",
		VESTACREDITDISCOVERCARDOTHER : "VestaCreditDiscoverOther",
		PROMOCREDIT : "PromoCredit"
};

/* Location agency type constants */
var locationsAgenyTypeConstant = {
	RELOADIT : "RELOADIT",
	BHNOPN : "BHNOPN",
	PRECASH1XP : "PRECASH1XP",
	PRECASHIC1XP : "PRECASHIC1XP",
	GREENDOT : "GREENDOT",
	WESTERN_UNION : "WESTERN UNION",
	READYLINK : "READYLINK"
};

/* Detail view receipt constants */
var detail_view_typeConstants = {
	PROMOCODE : "PromoCredit",
	BLACKHAWK : "Blackhawk",
	PRECASH : "PreCash",
	VANILLA : "InComm",
	CREDIT : "CREDIT",
	DEBIT : "DEBIT"
	
};

/* Detail receipt constants for status */
var detailReceiptConstants = {
	COMPLETEFAILED : "COMPLETE_FAILED",
	RETURNPENDING : "RETURN_PENDING",
	RETURNED : "RETURNED",
	RETURN : "RETURN", 
	CHECKOUT : "CHECKOUT",
	PAYMENTRETURNCREDIT : "PAYMENT_RETURN_CREDIT",
	PAID : "PAID",
	COMPLETESUCCESS : "COMPLETE_SUCCESS"
};

/* Manage cards constants */
var manageCard_typeConstants = {
		CREDIT : "Credit",
		DEBIT : "Debit"
};

/* Rejected status constants */
var rejected_typeConstants = {
		REJECTED : "REJECTED",
		SCHEDULED_POSTING_CATEGORY_CHANGED : "SCHEDULED_POSTING_CATEGORY_CHANGED",
		SCHEDULED_INVALID_PAYMENT_AMOUNT : "SCHEDULED_INVALID_PAYMENT_AMOUNT",
		SCHEDULED_VELOCITY_LIMIT_EXCEEDED : "SCHEDULED_VELOCITY_LIMIT_EXCEEDED",
		SCHEDULED_PAYMENT_CARD_FAILED : "SCHEDULED_PAYMENT_CARD_FAILED",
		SCHEDULED_PROGRAM_ENDED : "SCHEDULED_PROGRAM_ENDED",
		SCHEDULED_NOT_AUTHED : "SCHEDULED_NOT_AUTHED",
		SCHEDULED_POSTING_WINDOW_EXPIRED : "SCHEDULED_POSTING_WINDOW_EXPIRED",
		SCHEDULED_BAN_VELOCITY_LIMIT_EXCEEDED : "SCHEDULED_BAN_VELOCITY_LIMIT_EXCEEDED",
		SCHEDULED_CANCELLED_CARD_NO_LONGER_AVAILABLE : "SCHEDULED_CANCELLED_CARD_NO_LONGER_AVAILABLE"
};

/* Paid status constants */
var paid_typeConstatants = {
		PENDING	:	"PENDING",
		PAID	:	"PAID",
		SCHEDULED_PENDING	:	"SCHEDULED_PENDING",
		SCHEDULED_PROCESSING	:	"SCHEDULED_PROCESSING",
		IN_PROCESS	:	"IN_PROCESS",
		RETURN_PENDING : "RETURN_PENDING"
};